// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkhqpqyfupmptzgbolun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtraHFwcXlmdXBtcHR6Z2JvbHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTYyMjAsImV4cCI6MjA2NDUzMjIyMH0.dqZKO3FiZ2h4UJD7MkJ9rmCZJ0sBGyN8HjPflSKtPUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);